theme: minima
title: Careers at the Allen Institute for Neural Dynamics
description: <a href="https://alleninstitute.org/careers/">Join Us!</a>
github_username: AllenNeuralDynamics
author: Contact
email: neuraldynamics@alleninstitute.org
