theme: minima
title: Careers at the Allen Institute for Neural Dynamics
description: Join the Allen Institute for Neural Dynamics!
github_username: AllenNeuralDynamics
author: Contact
email: neuraldynamics@alleninstitute.org
