theme: minima
title: Careers at the Allen Institute for Neural Dynamics
description: [Join us!](https://alleninstitute.org/careers/)
github_username: AllenNeuralDynamics
author: Contact
email: neuraldynamics@alleninstitute.org
